import type { Course, CourseChapter } from "./course-data";

function createPlaylistChapters(videoIds: string[], titles: string[]): CourseChapter[] {
  return videoIds.map((id, index) => ({
    id: index + 1,
    title: titles[index] || `Chapter ${index + 1}`,
    topic: "Playlist Video",
    notes: ["Watch the video to learn more."],
    t: 0,
    videoId: id,
  }));
}

export const dsaPlaylistCourses: Course[] = [
  {
    slug: "dsa-basics",
    language: "C++ / Java",
    title: "DSA Basics",
    tagline: "The absolute basics of Data Structures and Algorithms.",
    description: "Start your DSA journey here. Covers time complexity, arrays, strings, and basic problem solving.",
    emoji: "🌱",
    level: "Beginner",
    hours: "~5 hrs",
    instructor: "Padho with Pratyush",
    teacher: "Pratyush",
    channel: "Padho with Pratyush",
    channelUrl: "https://www.youtube.com/@PadhoWithPratyush",
    videoId: "",
    playlistId: "PLbJhGqY-mq44tdtsBxMG00DMttxm9JspQ",
    accent: "from-green-400 to-emerald-600",
    type: "playlist",
    category: "Data Structures & Algorithms",
    tags: ["DSA", "Basics", "Beginner"],
    chapters: createPlaylistChapters(
      ["irqbmMNs2Bo", "q6z_UCBM5Ek", "UrsmFxEIp5k"],
      ["Introduction to DSA", "Time Complexity", "Space Complexity"]
    ),
  },
  {
    slug: "dsa-patterns",
    language: "C++ / Java",
    title: "All DSA Patterns",
    tagline: "Master the patterns, solve any problem.",
    description: "Don't memorize problems, learn the underlying patterns. Two pointers, sliding window, fast & slow pointers, and more.",
    emoji: "🧩",
    level: "Intermediate",
    hours: "~10 hrs",
    instructor: "Padho with Pratyush",
    teacher: "Pratyush",
    channel: "Padho with Pratyush",
    channelUrl: "https://www.youtube.com/@PadhoWithPratyush",
    videoId: "",
    playlistId: "PLbJhGqY-mq47k_WLUtzVjmarUm1EuXPj2",
    accent: "from-blue-400 to-indigo-600",
    type: "playlist",
    category: "Data Structures & Algorithms",
    tags: ["DSA", "Patterns", "Interviews"],
    chapters: createPlaylistChapters(
      ["irqbmMNs2Bo", "q6z_UCBM5Ek", "UrsmFxEIp5k"],
      ["Two Pointers Pattern", "Sliding Window Pattern", "Binary Search Pattern"]
    ),
  },
  {
    slug: "dsa-recursion",
    language: "C++ / Java",
    title: "Recursion Masterclass",
    tagline: "To understand recursion, you must first understand recursion.",
    description: "A deep dive into recursion. From basic base cases to complex backtracking problems.",
    emoji: "🔄",
    level: "Intermediate",
    hours: "~8 hrs",
    instructor: "Padho with Pratyush",
    teacher: "Pratyush",
    channel: "Padho with Pratyush",
    channelUrl: "https://www.youtube.com/@PadhoWithPratyush",
    videoId: "",
    playlistId: "PLbJhGqY-mq477LQUhVrkFKUB0B3BxHcjD",
    accent: "from-purple-400 to-fuchsia-600",
    type: "playlist",
    category: "Data Structures & Algorithms",
    tags: ["DSA", "Recursion", "Backtracking"],
    chapters: createPlaylistChapters(
      ["irqbmMNs2Bo", "q6z_UCBM5Ek", "UrsmFxEIp5k"],
      ["What is Recursion?", "Recursion Trees", "Backtracking Basics"]
    ),
  },
  {
    slug: "dsa-graphs",
    language: "C++ / Java",
    title: "Graph Series",
    tagline: "Conquer the most feared DSA topic.",
    description: "Comprehensive guide to Graphs. BFS, DFS, shortest paths, spanning trees, and topological sort.",
    emoji: "🕸️",
    level: "Advanced",
    hours: "~15 hrs",
    instructor: "Padho with Pratyush",
    teacher: "Pratyush",
    channel: "Padho with Pratyush",
    channelUrl: "https://www.youtube.com/@PadhoWithPratyush",
    videoId: "",
    playlistId: "PLbJhGqY-mq45iQU6ogidPlLdMuSzGanpC",
    accent: "from-slate-600 to-slate-900",
    type: "playlist",
    category: "Data Structures & Algorithms",
    tags: ["DSA", "Graphs", "Advanced"],
    chapters: createPlaylistChapters(
      ["video1_placeholder", "video2_placeholder", "video3_placeholder"],
      ["Graph Representation", "Breadth First Search (BFS)", "Depth First Search (DFS)"]
    ),
  },
  {
    slug: "ai-engineer-10-weeks",
    language: "Python",
    title: "AI Engineer In 10 Weeks",
    tagline: "From zero to building LLM applications.",
    description: "Learn how to build AI applications, work with LLMs, RAG, and prompt engineering over a 10-week curriculum.",
    emoji: "🤖",
    level: "Intermediate",
    hours: "~20 hrs",
    instructor: "Padho with Pratyush",
    teacher: "Pratyush",
    channel: "Padho with Pratyush",
    channelUrl: "https://www.youtube.com/@PadhoWithPratyush",
    videoId: "",
    playlistId: "PLW4OpyGE0RdY",
    accent: "from-rose-400 to-red-600",
    type: "playlist",
    category: "AI & Machine Learning",
    tags: ["AI", "LLM", "Python"],
    chapters: createPlaylistChapters(
      ["video1_placeholder", "video2_placeholder", "video3_placeholder"],
      ["Introduction to LLMs", "Prompt Engineering", "Building with LangChain"]
    ),
  },
];
