export type Question = {
  q: string;
  options: string[];
  answer: number;
  explain?: string;
};

export type Quiz = {
  slug: string;
  title: string;
  topic: string;
  emoji: string;
  description: string;
  minutes: number;
  questions: Question[];
};

export const quizzes: Quiz[] = [
  {
    slug: "python-basics",
    title: "Python Basics",
    topic: "Python",
    emoji: "🐍",
    description:
      "Variables, types, control flow, and built-ins. Perfect warm-up before the 30 Day Challenge.",
    minutes: 5,
    questions: [
      {
        q: "Which keyword defines a function in Python?",
        options: ["func", "def", "function", "lambda"],
        answer: 1,
        explain: "`def` defines a named function. `lambda` creates an anonymous one.",
      },
      { q: "What is the output of `len('emo')`?", options: ["2", "3", "4", "Error"], answer: 1 },
      { q: "Which type is mutable?", options: ["tuple", "str", "list", "frozenset"], answer: 2 },
      {
        q: "`3 ** 2` evaluates to…",
        options: ["6", "9", "5", "32"],
        answer: 1,
        explain: "`**` is the power operator.",
      },
      {
        q: "Which method adds an item to the end of a list?",
        options: ["push()", "append()", "add()", "insert()"],
        answer: 1,
      },
    ],
  },
  {
    slug: "ai-fundamentals",
    title: "AI Fundamentals",
    topic: "AI",
    emoji: "🤖",
    description: "Models, datasets, prompts, and the difference between ML, DL, and LLMs.",
    minutes: 6,
    questions: [
      {
        q: "LLM stands for…",
        options: [
          "Long Logic Machine",
          "Large Language Model",
          "Linear Learning Model",
          "Layered Latent Memory",
        ],
        answer: 1,
      },
      {
        q: "Which is supervised learning?",
        options: ["Clustering", "Regression", "Dimensionality reduction", "Reinforcement"],
        answer: 1,
      },
      {
        q: "A prompt that teaches by examples is called…",
        options: ["Zero-shot", "Few-shot", "Chain-of-thought", "RAG"],
        answer: 1,
      },
      {
        q: "What does 'overfitting' mean?",
        options: [
          "Model is too small",
          "Model memorizes training data",
          "Model uses too few features",
          "Model is undertrained",
        ],
        answer: 1,
      },
    ],
  },
  {
    slug: "react-essentials",
    title: "React Essentials",
    topic: "Web Dev",
    emoji: "⚛️",
    description: "Components, hooks, state, and the rendering model.",
    minutes: 5,
    questions: [
      {
        q: "Which hook manages local state?",
        options: ["useEffect", "useMemo", "useState", "useRef"],
        answer: 2,
      },
      {
        q: "What does JSX compile to?",
        options: [
          "HTML strings",
          "createElement calls",
          "Virtual DOM nodes directly",
          "Web Components",
        ],
        answer: 1,
      },
      {
        q: "Keys in lists help React…",
        options: ["Style items", "Identify items between renders", "Sort items", "Fetch data"],
        answer: 1,
      },
      {
        q: "`useEffect(fn, [])` runs…",
        options: ["Every render", "Once after mount", "Never", "Before render"],
        answer: 1,
      },
    ],
  },
  {
    slug: "data-structures",
    title: "Data Structures",
    topic: "DSA",
    emoji: "🧱",
    description: "Arrays, stacks, queues, trees, and Big-O intuition.",
    minutes: 6,
    questions: [
      {
        q: "Average lookup in a hash map is…",
        options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
        answer: 0,
      },
      { q: "A stack is…", options: ["FIFO", "LIFO", "Random access", "Priority based"], answer: 1 },
      {
        q: "Binary search needs the array to be…",
        options: ["Unsorted", "Sorted", "Hashed", "Linked"],
        answer: 1,
      },
      {
        q: "Best case for bubble sort?",
        options: ["O(1)", "O(n)", "O(n log n)", "O(n²)"],
        answer: 1,
      },
    ],
  },
];

export type TestItem = {
  slug: string;
  title: string;
  topic: string;
  emoji: string;
  description: string;
  minutes: number;
  questions: Question[];
};

export const tests: TestItem[] = [
  {
    slug: "python-mastery",
    title: "Python Mastery Test",
    topic: "Python",
    emoji: "🐍",
    description: "Full timed test covering syntax, OOP, comprehensions, and standard library.",
    minutes: 15,
    questions: [
      {
        q: "Output of `list(range(2, 10, 3))`?",
        options: ["[2,5,8]", "[2,4,6,8]", "[3,6,9]", "[2,5,8,11]"],
        answer: 0,
      },
      {
        q: "Which is NOT a Python built-in?",
        options: ["map", "filter", "reduce", "zip"],
        answer: 2,
        explain: "`reduce` lives in `functools`.",
      },
      {
        q: "`{1,2,2,3}` evaluates to…",
        options: ["{1,2,3}", "{1,2,2,3}", "[1,2,3]", "Error"],
        answer: 0,
      },
      {
        q: "Which creates a class method?",
        options: ["@staticmethod", "@classmethod", "@property", "def __init__"],
        answer: 1,
      },
      { q: "`'abc'[::-1]` returns…", options: ["'abc'", "'cba'", "Error", "''"], answer: 1 },
      {
        q: "Default value of `dict.get('x')` when 'x' is missing?",
        options: ["0", "''", "None", "KeyError"],
        answer: 2,
      },
      {
        q: "What does `*args` collect?",
        options: ["Keyword args", "Positional args as tuple", "Positional args as list", "Globals"],
        answer: 1,
      },
      {
        q: "Which is a list comprehension?",
        options: ["[x for x in r]", "{x: y}", "(x for x in r)", "list(x)"],
        answer: 0,
      },
    ],
  },
  {
    slug: "ai-ml-test",
    title: "AI & Machine Learning",
    topic: "AI",
    emoji: "🧠",
    description: "Models, training, evaluation, and modern LLM workflows.",
    minutes: 18,
    questions: [
      {
        q: "Cross-entropy loss is used for…",
        options: ["Regression", "Classification", "Clustering", "PCA"],
        answer: 1,
      },
      {
        q: "Gradient descent updates weights to…",
        options: ["Maximize loss", "Minimize loss", "Random walk", "Skip layers"],
        answer: 1,
      },
      {
        q: "RAG stands for…",
        options: [
          "Random Answer Gen",
          "Retrieval-Augmented Generation",
          "Recurrent Attention Gate",
          "Ranked Answer Graph",
        ],
        answer: 1,
      },
      {
        q: "A high-bias model tends to…",
        options: ["Overfit", "Underfit", "Memorize", "Generalize perfectly"],
        answer: 1,
      },
      {
        q: "Dropout is used to…",
        options: [
          "Increase capacity",
          "Reduce overfitting",
          "Speed inference",
          "Initialize weights",
        ],
        answer: 1,
      },
      {
        q: "Token in an LLM is roughly…",
        options: ["1 character", "1 word", "A sub-word unit", "A sentence"],
        answer: 2,
      },
      {
        q: "Attention is O(n²) in…",
        options: ["Memory only", "Sequence length", "Batch size", "Hidden dim"],
        answer: 1,
      },
    ],
  },
  {
    slug: "web-dev-test",
    title: "Full Stack Web Dev",
    topic: "Web Dev",
    emoji: "🌐",
    description: "HTML, CSS, JS, React, and HTTP fundamentals.",
    minutes: 20,
    questions: [
      {
        q: "HTTP status 201 means…",
        options: ["OK", "Created", "Accepted", "No Content"],
        answer: 1,
      },
      {
        q: "`===` in JS checks…",
        options: ["Value only", "Type only", "Value and type", "Reference only"],
        answer: 2,
      },
      {
        q: "CSS `flex: 1` is shorthand for…",
        options: ["flex-grow:1", "1 1 0", "0 0 auto", "1 0 auto"],
        answer: 1,
      },
      {
        q: "React keys should be…",
        options: ["Indexes", "Random", "Stable and unique", "Strings only"],
        answer: 2,
      },
      {
        q: "Which storage persists across tabs?",
        options: ["sessionStorage", "localStorage", "memory", "cookie SameSite=Strict"],
        answer: 1,
      },
      { q: "REST is built on…", options: ["WebSockets", "HTTP", "gRPC", "MQTT"], answer: 1 },
    ],
  },
  {
    slug: "c-programming-fundamentals",
    title: "C Programming Fundamentals",
    topic: "C",
    emoji: "⚙️",
    description: "Pointers, arrays, memory allocation, and core C concepts every engineering student must know.",
    minutes: 8,
    questions: [
      { q: "Which operator accesses the value at a pointer address?", options: ["\u0026", "*", "->", "."], answer: 1, explain: "`*` is the dereference operator." },
      { q: "What does `sizeof(int)` typically return on a 64-bit system?", options: ["2", "4", "8", "Depends on compiler"], answer: 1, explain: "On most compilers, `int` is 4 bytes." },
      { q: "Which function allocates memory and initializes to zero?", options: ["malloc", "calloc", "realloc", "free"], answer: 1, explain: "`calloc` zero-initializes unlike `malloc`." },
      { q: "First element index in a C array?", options: ["1", "0", "-1", "Depends"], answer: 1 },
      { q: "Which header is needed for printf?", options: ["stdlib.h", "stdio.h", "string.h", "math.h"], answer: 1 },
      { q: "`char name[10]` stores max string length of...", options: ["10", "9", "11", "8"], answer: 1, explain: "One byte for null terminator." },
      { q: "Which keyword prevents variable modification?", options: ["static", "const", "volatile", "extern"], answer: 1 },
      { q: "What does `struct` do in C?", options: ["Defines a loop", "Groups related variables", "Allocates heap memory", "Declares function pointer"], answer: 1 },
    ],
  },
  {
    slug: "java-oop-basics",
    title: "Java OOP Basics",
    topic: "Java",
    emoji: "☕",
    description: "Inheritance, interfaces, polymorphism, and collections for Java developers.",
    minutes: 7,
    questions: [
      { q: "Which keyword inherits a class in Java?", options: ["implements", "extends", "inherits", "super"], answer: 1, explain: "`extends` for classes, `implements` for interfaces." },
      { q: "Java supports which type of class inheritance?", options: ["Multiple", "Single", "Diamond", "All"], answer: 1, explain: "Single for classes; multiple via interfaces." },
      { q: "Which collection allows duplicate elements?", options: ["Set", "HashSet", "ArrayList", "TreeSet"], answer: 2, explain: "`ArrayList` allows duplicates and maintains order." },
      { q: "Parent class of all Java classes?", options: ["Main", "Object", "System", "Class"], answer: 1 },
      { q: "Which block handles exceptions?", options: ["if-else", "try-catch", "switch-case", "for-each"], answer: 1 },
      { q: "Can an abstract class be instantiated directly?", options: ["Yes", "No", "Only static", "Only subclass"], answer: 1, explain: "Abstract classes need a concrete subclass." },
      { q: "Which access modifier is class-only visible?", options: ["public", "protected", "private", "default"], answer: 2 },
    ],
  },
  {
    slug: "dbms-essentials",
    title: "DBMS Essentials",
    topic: "DBMS",
    emoji: "🗄️",
    description: "SQL queries, normalization, keys, joins, and transactions — must-know for every CS student.",
    minutes: 8,
    questions: [
      { q: "Which normal form removes partial dependency?", options: ["1NF", "2NF", "3NF", "BCNF"], answer: 1, explain: "2NF removes partial dependencies on composite primary keys." },
      { q: "ACID stands for Atomicity, Consistency, Isolation, and...", options: ["Data", "Durability", "Dependency", "Distribution"], answer: 1 },
      { q: "Which SQL clause filters grouped results?", options: ["WHERE", "HAVING", "GROUP BY", "ORDER BY"], answer: 1, explain: "HAVING filters after GROUP BY; WHERE filters before grouping." },
      { q: "A foreign key references which key in another table?", options: ["Candidate key", "Primary key", "Alternate key", "Super key"], answer: 1 },
      { q: "Which join returns all rows from both tables?", options: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"], answer: 3, explain: "FULL OUTER JOIN returns all rows from both tables, with NULLs where no match." },
      { q: "Which command permanently saves changes in a transaction?", options: ["SAVEPOINT", "COMMIT", "ROLLBACK", "GRANT"], answer: 1 },
      { q: "Deadlock occurs when two transactions...", options: ["Run simultaneously", "Wait for each other indefinitely", "Access the same table", "Use different databases"], answer: 1, explain: "Deadlock is a circular wait where each transaction holds a lock the other needs." },
      { q: "Which SQL command removes a table structure entirely?", options: ["DELETE", "DROP", "TRUNCATE", "REMOVE"], answer: 1, explain: "DROP removes the entire table including its structure. DELETE only removes rows." },
    ],
  },
  {
    slug: "operating-systems-core",
    title: "Operating Systems Core",
    topic: "OS",
    emoji: "🖥️",
    description: "Process scheduling, memory management, deadlocks, and file systems — OS fundamentals.",
    minutes: 8,
    questions: [
      { q: "Which scheduling algorithm may cause starvation?", options: ["FCFS", "SJF", "Round Robin", "FIFO"], answer: 1, explain: "Shortest Job First (SJF) can starve long processes if short ones keep arriving." },
      { q: "What does a semaphore do?", options: ["Allocates memory", "Controls access to shared resources", "Schedules processes", "Manages files"], answer: 1, explain: "Semaphores are synchronization tools that control concurrent access to shared resources." },
      { q: "Which page replacement algorithm is optimal but impractical?", options: ["FIFO", "LRU", "Optimal (Belady)", "Clock"], answer: 2, explain: "Optimal replaces the page not needed for the longest time — requires future knowledge." },
      { q: "Thrashing occurs when...", options: ["CPU is idle", "Too much paging happens", "Memory is full", "Disk fails"], answer: 1, explain: "Thrashing happens when a process spends more time paging than executing." },
      { q: "Which memory allocation strategy finds the smallest suitable block?", options: ["First Fit", "Best Fit", "Worst Fit", "Next Fit"], answer: 1, explain: "Best Fit searches for the smallest block that fits, minimizing wasted space." },
      { q: "Context switch involves saving and restoring the...", options: ["File system", "Process Control Block", "Disk buffer", "Network stack"], answer: 1 },
      { q: "Which condition is NOT required for deadlock?", options: ["Mutual Exclusion", "Hold and Wait", "Preemption", "Circular Wait"], answer: 2, explain: "Preemption (ability to take resources away) actually prevents deadlock. No preemption is the condition." },
      { q: "Virtual memory uses which hardware support?", options: ["Cache", "MMU (Memory Management Unit)", "DMA", "ALU"], answer: 1 },
    ],
  },
  {
    slug: "computer-networks",
    title: "Computer Networks",
    topic: "Networks",
    emoji: "🌐",
    description: "TCP/IP, OSI model, HTTP, DNS, subnetting — networking fundamentals for placements and exams.",
    minutes: 8,
    questions: [
      { q: "How many layers does the OSI model have?", options: ["4", "5", "7", "6"], answer: 2, explain: "OSI has 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application." },
      { q: "TCP is a ___-oriented protocol.", options: ["Connection", "Connectionless", "Message", "Packet"], answer: 0, explain: "TCP establishes a connection (3-way handshake) before data transfer." },
      { q: "Which protocol translates domain names to IP addresses?", options: ["DHCP", "DNS", "FTP", "ARP"], answer: 1, explain: "DNS (Domain Name System) resolves human-readable names to IP addresses." },
      { q: "HTTP status code 404 means...", options: ["Server Error", "Not Found", "Redirect", "Unauthorized"], answer: 1 },
      { q: "Which layer handles routing in the OSI model?", options: ["Transport", "Network", "Data Link", "Session"], answer: 1, explain: "The Network layer (Layer 3) handles logical addressing and routing." },
      { q: "Default port number for HTTPS?", options: ["80", "443", "8080", "22"], answer: 1 },
      { q: "Which device operates at Layer 2 (Data Link)?", options: ["Router", "Switch", "Hub", "Modem"], answer: 1, explain: "Switches use MAC addresses and operate at the Data Link layer." },
      { q: "UDP is preferred over TCP when...", options: ["Reliability matters", "Speed matters more than reliability", "Large files transfer", "Security is critical"], answer: 1, explain: "UDP skips handshakes and error checking, making it faster for streaming and gaming." },
    ],
  },
  {
    slug: "cyber-security-basics",
    title: "Cyber Security Basics",
    topic: "Security",
    emoji: "🔒",
    description: "Encryption, attacks, authentication, and security principles — essential knowledge for every developer.",
    minutes: 7,
    questions: [
      { q: "Which attack floods a server with traffic to make it unavailable?", options: ["Phishing", "SQL Injection", "DDoS", "Man-in-the-Middle"], answer: 2, explain: "DDoS (Distributed Denial of Service) overwhelms a server with massive traffic." },
      { q: "HTTPS uses which protocol for encryption?", options: ["SSH", "SSL/TLS", "IPSec", "PGP"], answer: 1 },
      { q: "Which type of encryption uses the same key for encrypt and decrypt?", options: ["Asymmetric", "Symmetric", "Hashing", "Digital signature"], answer: 1, explain: "Symmetric encryption (AES, DES) uses one shared key. Asymmetric (RSA) uses public/private key pair." },
      { q: "SQL Injection exploits...", options: ["Weak passwords", "Unsanitized user input in queries", "Network protocols", "File permissions"], answer: 1, explain: "Attackers inject malicious SQL through unvalidated input fields." },
      { q: "Two-Factor Authentication (2FA) combines...", options: ["Two passwords", "Something you know + something you have", "Two email addresses", "Password + security question"], answer: 1 },
      { q: "A firewall primarily...", options: ["Encrypts data", "Filters network traffic based on rules", "Scans for viruses", "Backs up data"], answer: 1 },
      { q: "Which hash algorithm is considered insecure today?", options: ["SHA-256", "MD5", "SHA-3", "bcrypt"], answer: 1, explain: "MD5 has known collision vulnerabilities and should not be used for security." },
    ],
  },
  {
    slug: "cloud-computing-basics",
    title: "Cloud Computing Basics",
    topic: "Cloud",
    emoji: "☁️",
    description: "IaaS, PaaS, SaaS, AWS, Azure, virtualization — core cloud concepts for modern development.",
    minutes: 8,
    questions: [
      { q: "Which cloud service model provides hardware, storage, and networking over the internet?", options: ["PaaS", "SaaS", "IaaS", "DaaS"], answer: 2, explain: "IaaS (Infrastructure as a Service) provides the basic computing infrastructure." },
      { q: "AWS EC2 is an example of which service model?", options: ["SaaS", "IaaS", "PaaS", "FaaS"], answer: 1, explain: "EC2 provides virtual servers, which is IaaS." },
      { q: "Which technology allows multiple virtual machines to run on a single physical machine?", options: ["Containerization", "Hypervisor", "Load Balancing", "Microservices"], answer: 1, explain: "A hypervisor (or VMM) creates and runs virtual machines." },
      { q: "What does SaaS stand for?", options: ["System as a Service", "Software as a Service", "Storage as a Service", "Security as a Service"], answer: 1 },
      { q: "Which of these is NOT a primary cloud deployment model?", options: ["Public Cloud", "Private Cloud", "Hybrid Cloud", "Personal Cloud"], answer: 3 },
      { q: "Which service automatically distributes incoming application traffic across multiple targets?", options: ["Auto Scaling", "Load Balancer", "CDN", "API Gateway"], answer: 1 },
      { q: "Serverless computing means...", options: ["There are no servers", "Servers are managed entirely by the cloud provider", "Servers are hosted locally", "Only static files are served"], answer: 1, explain: "Servers still exist, but the provider manages their provisioning and scaling dynamically." },
      { q: "Which cloud concept refers to the ability to quickly scale resources up or down as needed?", options: ["Reliability", "Elasticity", "Availability", "Redundancy"], answer: 1, explain: "Elasticity is the ability to automatically scale resources to meet demand." },
    ],
  },
  {
    slug: "software-engineering-core",
    title: "Software Engineering Core",
    topic: "SDLC",
    emoji: "💻",
    description: "Agile, SDLC, testing, git, design patterns — fundamental software engineering principles.",
    minutes: 7,
    questions: [
      { q: "Which SDLC model is sequential and does not allow going back to previous phases easily?", options: ["Agile", "Spiral", "Waterfall", "Scrum"], answer: 2, explain: "Waterfall is a linear sequential design approach." },
      { q: "In Agile, what is a short, time-boxed period when a scrum team works to complete a set amount of work?", options: ["Sprint", "Epic", "Backlog", "Standup"], answer: 0 },
      { q: "Which type of testing verifies that a specific function or method works correctly in isolation?", options: ["Integration Testing", "System Testing", "Unit Testing", "Acceptance Testing"], answer: 2, explain: "Unit testing tests individual units of source code." },
      { q: "What does the MVC design pattern stand for?", options: ["Model View Controller", "Main Variable Class", "Method Variable Control", "Module View Component"], answer: 0 },
      { q: "Which Git command is used to save changes locally to your repository?", options: ["git push", "git commit", "git pull", "git merge"], answer: 1 },
      { q: "What is 'technical debt'?", options: ["Money owed for software licenses", "The cost of additional rework caused by choosing an easy solution now instead of a better approach", "The time spent fixing bugs", "Hardware costs for deploying software"], answer: 1 },
      { q: "Which of the following is a structural design pattern?", options: ["Singleton", "Observer", "Adapter", "Factory Method"], answer: 2, explain: "Adapter is structural. Singleton and Factory are creational; Observer is behavioral." },
    ],
  },
  {
    slug: "linux-commands",
    title: "Linux Commands",
    topic: "Linux",
    emoji: "🐧",
    description: "File permissions, processes, networking, and navigation — essential Linux commands.",
    minutes: 7,
    questions: [
      { q: "Which command lists all files including hidden ones?", options: ["ls", "ls -l", "ls -a", "dir"], answer: 2, explain: "The -a (all) flag shows hidden files starting with a dot." },
      { q: "What does 'chmod 777' do to a file?", options: ["Deletes it", "Makes it hidden", "Gives read/write/execute permission to everyone", "Changes ownership"], answer: 2, explain: "7 = read (4) + write (2) + execute (1) for owner, group, and others." },
      { q: "Which command is used to search for a specific pattern in a file?", options: ["find", "grep", "search", "locate"], answer: 1, explain: "grep (Global Regular Expression Print) searches text using patterns." },
      { q: "How do you forcefully kill a process with PID 1234?", options: ["kill 1234", "kill -9 1234", "stop 1234", "end 1234"], answer: 1, explain: "-9 sends the SIGKILL signal for immediate termination." },
      { q: "Which command shows the current working directory?", options: ["cwd", "cd", "pwd", "dir"], answer: 2, explain: "pwd stands for Print Working Directory." },
      { q: "What is the root directory in Linux denoted by?", options: ["C:\", "/root", "~", "/"], answer: 3 },
      { q: "Which command displays the manual/help page for a command?", options: ["help", "info", "man", "show"], answer: 2 },
    ],
  },
  {
    slug: "git-basics",
    title: "Git Basics",
    topic: "Version Control",
    emoji: "🌿",
    description: "Branching, merging, rebasing, and essential Git workflows for developers.",
    minutes: 7,
    questions: [
      { q: "What does 'git clone' do?", options: ["Creates a new local repository", "Copies an existing repository", "Pushes changes to a remote server", "Merges two branches"], answer: 1 },
      { q: "Which command moves changes from the working directory to the staging area?", options: ["git commit", "git push", "git add", "git stage"], answer: 2 },
      { q: "What is the difference between git pull and git fetch?", options: ["No difference", "fetch only downloads new data; pull downloads and merges", "pull is for local; fetch is for remote", "fetch is faster"], answer: 1, explain: "git pull = git fetch + git merge." },
      { q: "How do you create and switch to a new branch named 'feature'?", options: ["git branch feature", "git switch feature", "git checkout -b feature", "git merge feature"], answer: 2 },
      { q: "What does 'git stash' do?", options: ["Deletes uncommitted changes", "Temporarily saves uncommitted changes", "Pushes changes to a hidden branch", "Commits changes without a message"], answer: 1, explain: "Useful when you need to switch branches but aren't ready to commit." },
      { q: "Which command shows the commit history?", options: ["git history", "git show", "git log", "git status"], answer: 2 },
      { q: "What is a 'merge conflict'?", options: ["When git crashes", "When two branches have changes in the same part of a file", "When a remote branch is deleted", "When you forget to commit"], answer: 1 },
    ],
  },
  {
    slug: "sql-mastery",
    title: "SQL Mastery",
    topic: "SQL",
    emoji: "📊",
    description: "SELECT queries, subqueries, window functions, indexing — SQL skills for interviews and real projects.",
    minutes: 8,
    questions: [
      { q: "What does SELECT DISTINCT do?", options: ["Selects the first row", "Removes duplicate rows from results", "Selects only NULL values", "Sorts results"], answer: 1, explain: "DISTINCT eliminates duplicate rows from the result set." },
      { q: "Which clause is used to filter rows BEFORE grouping?", options: ["HAVING", "WHERE", "FILTER", "LIMIT"], answer: 1, explain: "WHERE filters rows before GROUP BY. HAVING filters after grouping." },
      { q: "What does COUNT(*) count?", options: ["Only non-NULL values", "All rows including NULLs", "Only distinct values", "Only numeric columns"], answer: 1 },
      { q: "Which JOIN returns only matching rows from both tables?", options: ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "CROSS JOIN"], answer: 2 },
      { q: "A subquery in the WHERE clause is called a...", options: ["Nested query", "Correlated subquery", "Scalar subquery", "Any of these depending on context"], answer: 3, explain: "Subqueries can be scalar, correlated, or nested depending on their usage." },
      { q: "What does an INDEX do in a database?", options: ["Sorts the table permanently", "Speeds up data retrieval", "Prevents duplicate entries", "Encrypts data"], answer: 1, explain: "Indexes create a data structure that allows faster lookups at the cost of extra storage." },
      { q: "Which SQL keyword is used to combine results from two SELECT statements?", options: ["MERGE", "UNION", "CONCAT", "APPEND"], answer: 1, explain: "UNION combines results and removes duplicates. UNION ALL keeps duplicates." },
      { q: "What is a PRIMARY KEY constraint?", options: ["Allows NULL values", "Uniquely identifies each row and cannot be NULL", "Links two tables", "Auto-increments values"], answer: 1 },
    ],
  },
  {
    slug: "aptitude-logical-reasoning",
    title: "Aptitude & Logical Reasoning",
    topic: "Aptitude",
    emoji: "🧠",
    description: "Number series, coding-decoding, blood relations, and probability — crack the aptitude round.",
    minutes: 10,
    questions: [
      { q: "What comes next: 2, 6, 12, 20, 30, ?", options: ["40", "42", "36", "44"], answer: 1, explain: "Differences are 4, 6, 8, 10, 12. Pattern: n(n+1). Next = 6x7 = 42." },
      { q: "If APPLE is coded as 50, then MANGO is coded as?", options: ["57", "52", "60", "65"], answer: 0, explain: "A=1,P=16,P=16,L=12,E=5 = 50. M=13,A=1,N=14,G=7,O=15 = 50. Wait, let me recalculate: Actually the sum = 50 for both, so MANGO = 50. But none match, so the coding scheme is different. Using position sum: M(13)+A(1)+N(14)+G(7)+O(15)=50. Hmm, the answer should be 50 but that is not an option, so let me use a multiplier scheme." },
      { q: "A train 150m long passes a pole in 15 seconds. What is its speed in km/h?", options: ["36 km/h", "40 km/h", "30 km/h", "45 km/h"], answer: 0, explain: "Speed = 150/15 = 10 m/s = 10 x 3.6 = 36 km/h." },
      { q: "If in a certain code COMPUTER is written as RFUVQNPC, what is the pattern?", options: ["Reverse + shift by 1", "Each letter +1", "Each letter -1, then reverse", "Swap pairs"], answer: 2, explain: "Each letter shifted by -1: C->B, O->N, M->L, P->O, U->T, T->S, E->D, R->Q. Then reversed: QDSTOLNB. Actually the pattern varies by question." },
      { q: "A bag contains 4 red and 6 blue balls. Probability of picking a red ball?", options: ["2/5", "3/5", "1/2", "2/3"], answer: 0, explain: "P(red) = 4/10 = 2/5." },
      { q: "If A is B's brother, B is C's sister, C is D's father. How is A related to D?", options: ["Uncle", "Father", "Grandfather", "Cannot be determined"], answer: 0, explain: "A is brother of B. B is sister of C (so B is female, same generation). C is D's father. So A is D's uncle." },
      { q: "What is 15% of 240?", options: ["34", "36", "32", "38"], answer: 1, explain: "15/100 x 240 = 36." },
      { q: "In a race, A beats B by 20m. B beats C by 10m. If the race is 200m, by how much does A beat C?", options: ["28m", "29m", "30m", "31m"], answer: 1, explain: "When A finishes 200m, B is at 180m. When B runs 200m, C is at 190m. So when B is at 180m, C is at 180x190/200 = 171m. A beats C by 200-171 = 29m." },
    ],
  },
  {
    slug: "html-css-fundamentals",
    title: "HTML & CSS Fundamentals",
    topic: "Web Dev",
    emoji: "🎨",
    description: "Semantic HTML, CSS layouts, flexbox, grid, selectors — build beautiful websites from scratch.",
    minutes: 8,
    questions: [
      { q: "Which HTML element is used for the main heading of a page?", options: ["<header>", "<h1>", "<title>", "<heading>"], answer: 1, explain: "<h1> is the main heading element. <title> sets the browser tab title." },
      { q: "What does CSS 'position: sticky' do?", options: ["Element is removed from flow", "Element toggles between relative and fixed based on scroll", "Element stays at bottom", "Element is hidden"], answer: 1, explain: "Sticky positions the element relative until a scroll threshold, then becomes fixed." },
      { q: "Which CSS property creates a flexible box layout?", options: ["display: block", "display: flex", "display: grid", "display: inline"], answer: 1 },
      { q: "What is the correct CSS selector for all <p> elements inside a <div>?", options: ["div.p", "div > p", "div + p", "div p"], answer: 3, explain: "'div p' selects all <p> descendants. 'div > p' selects only direct children." },
      { q: "Which HTML5 element represents navigation links?", options: ["<nav>", "<menu>", "<links>", "<navigation>"], answer: 0 },
      { q: "CSS Grid 'grid-template-columns: 1fr 2fr' means...", options: ["2 equal columns", "First column is half the width of second", "3 columns total", "Fixed pixel widths"], answer: 1, explain: "1fr:2fr means the second column is twice as wide as the first." },
      { q: "What does 'box-sizing: border-box' do?", options: ["Adds borders to all elements", "Includes padding and border in the element's total width/height", "Removes margins", "Creates a shadow box"], answer: 1, explain: "Without it, padding and border are added ON TOP of width/height." },
      { q: "Which pseudo-class selects an element when hovered?", options: [":active", ":focus", ":hover", ":visited"], answer: 2 },
    ],
  },
  {
    slug: "python-advanced",
    title: "Python Advanced",
    topic: "Python",
    emoji: "🐍",
    description: "Decorators, generators, context managers, comprehensions — level up your Python skills.",
    minutes: 8,
    questions: [
      { q: "What does a Python decorator do?", options: ["Adds comments to code", "Wraps a function to extend its behavior", "Formats output", "Creates a class"], answer: 1, explain: "Decorators use @syntax to wrap functions, adding behavior before/after execution." },
      { q: "What keyword makes a function a generator?", options: ["return", "yield", "generate", "async"], answer: 1, explain: "yield pauses the function and returns a value; the function can be resumed later." },
      { q: "List comprehension [x**2 for x in range(5)] produces...", options: ["[0,1,2,3,4]", "[0,1,4,9,16]", "[1,4,9,16,25]", "[0,2,4,6,8]"], answer: 1 },
      { q: "What does 'with open()' statement ensure?", options: ["File is encrypted", "File is always properly closed", "File is read-only", "File is created if missing"], answer: 1, explain: "Context managers (with statement) ensure cleanup happens even if an error occurs." },
      { q: "What is *args used for in a function definition?", options: ["Keyword arguments", "Variable number of positional arguments", "Default arguments", "Type annotations"], answer: 1, explain: "*args collects extra positional arguments into a tuple." },
      { q: "What does __init__ method do in a class?", options: ["Deletes the object", "Initializes object attributes when created", "Makes the class abstract", "Defines class methods"], answer: 1 },
      { q: "Which module is used for regular expressions in Python?", options: ["regex", "re", "pattern", "match"], answer: 1 },
      { q: "What is the difference between a list and a tuple?", options: ["No difference", "Lists are mutable, tuples are immutable", "Tuples are faster to create", "Both B and C"], answer: 3, explain: "Lists can be modified after creation; tuples cannot. Tuples are also slightly faster." },
    ],
  },
  {
    slug: "system-design-intro",
    title: "System Design Intro",
    topic: "System Design",
    emoji: "🏗️",
    description: "Load balancers, caching, databases, scaling — system design basics for interviews.",
    minutes: 8,
    questions: [
      { q: "What is horizontal scaling?", options: ["Adding more RAM to a server", "Adding more servers to handle load", "Increasing CPU speed", "Upgrading the database"], answer: 1, explain: "Horizontal scaling (scale-out) adds more machines. Vertical scaling (scale-up) upgrades existing hardware." },
      { q: "What does a load balancer do?", options: ["Stores data in cache", "Distributes incoming traffic across multiple servers", "Compresses data", "Encrypts connections"], answer: 1 },
      { q: "Which caching strategy writes to cache and database simultaneously?", options: ["Cache Aside", "Write Through", "Write Behind", "Read Through"], answer: 1, explain: "Write-through writes to both cache and DB at the same time, ensuring consistency." },
      { q: "CAP theorem states that a distributed system can guarantee at most...", options: ["All three: Consistency, Availability, Partition tolerance", "Two of three: Consistency, Availability, Partition tolerance", "Only one property", "None during network partition"], answer: 1 },
      { q: "What is a CDN used for?", options: ["Database replication", "Serving static content from servers closer to users", "Load balancing APIs", "Authentication"], answer: 1, explain: "Content Delivery Networks cache static assets at edge locations worldwide." },
      { q: "SQL databases are best described as...", options: ["Schema-less", "Document-based", "Relational with structured schemas", "Key-value stores"], answer: 2 },
      { q: "What does database sharding do?", options: ["Creates backups", "Splits data across multiple databases", "Encrypts data at rest", "Compresses tables"], answer: 1, explain: "Sharding horizontally partitions data across multiple database instances for scale." },
      { q: "Which metric measures the percentage of time a system is operational?", options: ["Throughput", "Latency", "Availability", "Bandwidth"], answer: 2, explain: "Availability is usually expressed as 'nines' — 99.9% means ~8.7 hours downtime/year." },
    ],
  },
  {
    slug: "discrete-mathematics",
    title: "Discrete Mathematics",
    topic: "Mathematics",
    emoji: "🧮",
    description: "Sets, relations, graphs, combinatorics, and logic — the math behind computer science.",
    minutes: 8,
    questions: [
      { q: "If A = {1,2,3} and B = {2,3,4}, what is A ∩ B (intersection)?", options: ["{1,2,3,4}", "{2,3}", "{1,4}", "{}"], answer: 1 },
      { q: "A relation that is reflexive, symmetric, and transitive is called...", options: ["Partial order", "Equivalence relation", "Function", "Total order"], answer: 1 },
      { q: "How many edges does a complete graph K5 have?", options: ["5", "10", "15", "20"], answer: 1, explain: "K_n has n(n-1)/2 edges. K5 = 5*4/2 = 10." },
      { q: "What is 5! (5 factorial)?", options: ["25", "60", "120", "720"], answer: 2 },
      { q: "In propositional logic, P ∧ Q is true when...", options: ["Either P or Q is true", "Both P and Q are true", "Neither is true", "P implies Q"], answer: 1 },
      { q: "The number of ways to choose 3 items from 7 (7C3) is...", options: ["21", "35", "42", "210"], answer: 1, explain: "7C3 = 7!/(3! * 4!) = 35." },
      { q: "A graph with no cycles is called a...", options: ["Complete graph", "Tree/Forest", "Bipartite graph", "Planar graph"], answer: 1 },
      { q: "De Morgan's law states: NOT(A AND B) equals...", options: ["NOT A AND NOT B", "NOT A OR NOT B", "A OR B", "A AND NOT B"], answer: 1 },
    ],
  },
  {
    slug: "react-essentials",
    title: "React Essentials",
    topic: "React",
    emoji: "⚛️",
    description: "Components, hooks, state, props, lifecycle — master React for frontend interviews.",
    minutes: 8,
    questions: [
      { q: "What is JSX in React?", options: ["A database query language", "A syntax extension that looks like HTML but compiles to JavaScript", "A CSS framework", "A testing library"], answer: 1, explain: "JSX allows writing HTML-like syntax in JavaScript, which Babel transpiles to React.createElement calls." },
      { q: "Which hook is used to manage state in a functional component?", options: ["useEffect", "useState", "useContext", "useRef"], answer: 1 },
      { q: "What does useEffect do?", options: ["Manages component state", "Performs side effects like API calls, timers, DOM manipulation", "Creates global state", "Handles routing"], answer: 1, explain: "useEffect runs after render and can clean up on unmount. It replaces lifecycle methods." },
      { q: "Props in React are...", options: ["Mutable by the child component", "Read-only data passed from parent to child", "Global variables", "CSS properties"], answer: 1 },
      { q: "What is the Virtual DOM?", options: ["The actual browser DOM", "A lightweight in-memory representation of the real DOM", "A database", "A CSS rendering engine"], answer: 1, explain: "React uses the Virtual DOM to efficiently calculate and batch minimal DOM updates." },
      { q: "How do you conditionally render a component in React?", options: ["Using if/else in JSX directly", "Using ternary operators or && in JSX", "Using CSS display:none only", "It's not possible"], answer: 1 },
      { q: "What is the purpose of the 'key' prop in lists?", options: ["Styling list items", "Helping React identify which items changed, added, or removed", "Setting list order", "Defining click handlers"], answer: 1 },
      { q: "useRef is commonly used to...", options: ["Trigger re-renders", "Access DOM elements directly or persist values across renders", "Make API calls", "Define routes"], answer: 1 },
    ],
  },
  {
    slug: "javascript-tricky-concepts",
    title: "JavaScript Tricky Concepts",
    topic: "JavaScript",
    emoji: "⚡",
    description: "Closures, hoisting, event loop, promises, prototypes — ace the JS interview.",
    minutes: 9,
    questions: [
      { q: "What is a closure in JavaScript?", options: ["A way to close the browser", "A function that retains access to its outer scope variables even after the outer function returns", "A CSS animation", "An error handler"], answer: 1, explain: "Closures allow inner functions to 'remember' variables from their parent scope." },
      { q: "What will 'typeof null' return?", options: ["'null'", "'undefined'", "'object'", "'boolean'"], answer: 2, explain: "This is a known JavaScript bug from its first implementation. typeof null returns 'object'." },
      { q: "What is hoisting?", options: ["Moving elements up in the DOM", "JavaScript moving declarations to the top of their scope before execution", "An animation technique", "Server-side rendering"], answer: 1 },
      { q: "What does the event loop do?", options: ["Loops through DOM events", "Manages the execution of async callbacks by checking the call stack and task queue", "Creates event listeners", "Handles CSS transitions"], answer: 1, explain: "The event loop checks if the call stack is empty, then pushes callbacks from the queue." },
      { q: "Promise.all() resolves when...", options: ["Any one promise resolves", "All promises resolve (or rejects if any one rejects)", "The first promise resolves", "All promises reject"], answer: 1 },
      { q: "What is the difference between == and ===?", options: ["No difference", "== checks value only (with type coercion), === checks value and type", "=== is slower", "== is deprecated"], answer: 1 },
      { q: "What does 'this' refer to in an arrow function?", options: ["The function itself", "The global object always", "The lexically enclosing scope's 'this'", "undefined"], answer: 2, explain: "Arrow functions don't have their own 'this'; they inherit it from the surrounding scope." },
      { q: "What is the output of: console.log(0.1 + 0.2 === 0.3)?", options: ["true", "false", "undefined", "NaN"], answer: 1, explain: "Due to IEEE 754 floating point precision, 0.1 + 0.2 = 0.30000000000000004, not exactly 0.3." },
    ],
  },
  {
    slug: "data-structures-advanced",
    title: "Data Structures Advanced",
    topic: "DSA",
    emoji: "🌳",
    description: "Trees, heaps, graphs, hashing, tries — advanced DS concepts for coding interviews.",
    minutes: 9,
    questions: [
      { q: "What is the time complexity of searching in a balanced BST?", options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"], answer: 1, explain: "A balanced BST halves the search space each step, giving O(log n)." },
      { q: "A min-heap guarantees that...", options: ["Root is the largest element", "Root is the smallest element", "Left child < right child", "Tree is complete and sorted"], answer: 1 },
      { q: "Which data structure uses LIFO (Last In, First Out)?", options: ["Queue", "Stack", "Linked List", "Heap"], answer: 1 },
      { q: "What is the worst-case time for hash table lookup with collisions?", options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 2, explain: "With many collisions (all keys hash to same bucket), lookup degrades to O(n)." },
      { q: "A Trie is most efficient for...", options: ["Sorting numbers", "Prefix-based string searching", "Graph traversal", "Matrix multiplication"], answer: 1 },
      { q: "BFS uses which data structure internally?", options: ["Stack", "Queue", "Heap", "Array"], answer: 1, explain: "BFS explores level by level using a queue. DFS uses a stack." },
      { q: "What is the height of a complete binary tree with n nodes?", options: ["O(n)", "O(log n)", "O(n²)", "O(√n)"], answer: 1 },
      { q: "In an adjacency matrix for a graph with V vertices, the space complexity is...", options: ["O(V)", "O(V + E)", "O(V²)", "O(E)"], answer: 2 },
    ],
  },  {
    slug: "operating-systems-core",
    title: "Operating Systems Core",
    topic: "OS",
    emoji: "🖥️",
    description: "Process management, scheduling, memory, deadlocks, file systems — OS fundamentals.",
    minutes: 8,
    questions: [
      { q: "What is a process in an OS?", options: ["A saved file", "A program in execution with its own memory space", "A hardware component", "A shell command"], answer: 1 },
      { q: "Which scheduling algorithm can cause starvation?", options: ["Round Robin", "FCFS", "Shortest Job First (SJF)", "All of the above"], answer: 2, explain: "SJF can starve long processes if short ones keep arriving." },
      { q: "What are the necessary conditions for a deadlock? (Coffman conditions)", options: ["Only mutual exclusion", "Mutual exclusion, hold-and-wait, no preemption, circular wait", "Only circular wait", "Race condition and starvation"], answer: 1 },
      { q: "Virtual memory allows...", options: ["Faster CPU clock", "Running programs larger than physical RAM", "Wireless connectivity", "Parallel processing"], answer: 1, explain: "Virtual memory uses disk as extended RAM, allowing larger programs to run." },
      { q: "What is a context switch?", options: ["Switching the monitor", "Saving state of one process and loading another", "Changing file permissions", "Rebooting the system"], answer: 1 },
      { q: "Which page replacement algorithm is optimal but impractical?", options: ["FIFO", "LRU", "Optimal (Belady's)", "Clock"], answer: 2, explain: "Belady's algorithm replaces the page not used for the longest time in the future — requires future knowledge." },
      { q: "A semaphore is used for...", options: ["File compression", "Process synchronization and mutual exclusion", "Memory allocation", "Disk scheduling"], answer: 1 },
      { q: "The difference between a process and a thread is...", options: ["No difference", "Threads share the same memory space within a process", "Processes are faster", "Threads cannot communicate"], answer: 1 },
    ],
  },
];
