import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { Loader2, CalendarClock, Zap, Copy, Check, Download } from "lucide-react";
import { callEmoIq, type PlanResult } from "@/lib/emoiq/api";
import { PdfDropzone } from "@/components/site/PdfDropzone";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/auth";

export const Route = createFileRoute("/emoiq/plan")({
  component: PlanPage,
});

function PlanPage() {
  const { user } = useAuth();
  const [subject, setSubject] = useState("");
  const [weak, setWeak] = useState("");
  const [days, setDays] = useState(7);
  const [mode, setMode] = useState<"normal" | "crash">("normal");
  const [pdfContext, setPdfContext] = useState("");
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState<PlanResult | null>(null);
  const [copied, setCopied] = useState(false);

  function planToText(p: PlanResult): string {
    const lines: string[] = [];
    lines.push(`📋 ${p.headline}`);
    lines.push("");
    lines.push(`Strategy: ${p.strategy}`);
    lines.push("");
    for (const d of p.days ?? []) {
      lines.push(`--- ${mode === "crash" ? `Block ${d.day}` : `Day ${d.day}`} (${d.hours}h) ---`);
      lines.push(`Focus: ${d.focus}`);
      lines.push(`Topics: ${d.topics?.join(", ")}`);
      lines.push("Tasks:");
      for (const t of d.tasks ?? []) {
        lines.push(`  • ${t}`);
      }
      lines.push("");
    }
    if (p.skip?.length) {
      lines.push("Skip for now: " + p.skip.join(", "));
    }
    lines.push("");
    lines.push("— Generated by EMO Learners (emolearners.vercel.app)");
    return lines.join("\n");
  }

  function copyPlan() {
    if (!plan) return;
    navigator.clipboard.writeText(planToText(plan));
    setCopied(true);
    toast.success("Plan copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  }

  function downloadPlan() {
    if (!plan) return;
    const text = planToText(plan);
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `study-plan-${subject.trim().toLowerCase().replace(/\s+/g, "-") || "plan"}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Plan downloaded");
  }

  async function generate() {
    if (!subject.trim()) {
      toast.error("Subject required");
      return;
    }
    setLoading(true);
    setPlan(null);
    try {
      const r = await callEmoIq<PlanResult>("plan", {
        subject,
        weakTopics: weak
          .split(",")
          .map((t) => t.trim())
          .filter(Boolean),
        daysLeft: mode === "crash" ? 1 : days,
        mode,
        notes: pdfContext || undefined,
      });
      setPlan(r);
      if (user) {
        await supabase.from("study_plans").insert({
          user_id: user.id,
          subject,
          days_left: mode === "crash" ? 1 : days,
          mode,
          plan: r as never,
          active: true,
        });
      }
      toast.success("Plan ready");
    } catch (e) {
      toast.error((e as Error).message);
    } finally {
      setLoading(false);
    }
  }

  return (
    <section className="mx-auto max-w-5xl px-4 py-14">
      <h1 className="font-display text-3xl font-bold tracking-tighter md:text-5xl">
        Study <span className="grad-text">Plan</span>
      </h1>
      <p className="mt-3 text-muted-foreground">
        A day-by-day plan tuned to your weak topics and time left. Try Last-24h mode if the exam is
        tomorrow.
      </p>

      <div className="mt-8 grid gap-4 md:grid-cols-2">
        <input
          className="rounded-xl border border-border bg-surface px-4 py-3 text-sm focus:border-primary"
          placeholder="Subject"
          value={subject}
          onChange={(e) => setSubject(e.target.value)}
        />
        <input
          className="rounded-xl border border-border bg-surface px-4 py-3 text-sm focus:border-primary"
          placeholder="Weak topics (comma-separated)"
          value={weak}
          onChange={(e) => setWeak(e.target.value)}
        />
        <div className="flex items-center gap-3">
          <label className="text-sm text-muted-foreground">Days left</label>
          <input
            type="number"
            min={1}
            max={60}
            value={days}
            onChange={(e) => setDays(Number(e.target.value))}
            className="w-24 rounded-xl border border-border bg-surface px-3 py-2 text-sm focus:border-primary"
            disabled={mode === "crash"}
          />
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => setMode("normal")}
            className={`inline-flex items-center gap-2 rounded-full border px-4 py-2 font-mono text-[11px] uppercase tracking-widest ${mode === "normal" ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground"}`}
          >
            <CalendarClock className="h-3 w-3" /> Normal
          </button>
          <button
            type="button"
            onClick={() => setMode("crash")}
            className={`inline-flex items-center gap-2 rounded-full border px-4 py-2 font-mono text-[11px] uppercase tracking-widest ${mode === "crash" ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground"}`}
          >
            <Zap className="h-3 w-3" /> Last 24h
          </button>
        </div>
      </div>

      <div className="mt-4">
        <PdfDropzone
          label="Upload syllabus / notes PDFs (optional)"
          hint="AI uses their contents to tailor your plan."
          onText={(t) => setPdfContext(t)}
        />
      </div>

      <button
        onClick={generate}
        disabled={loading}
        className="mt-6 inline-flex items-center gap-2 rounded-full px-6 py-3 font-mono text-xs font-bold uppercase tracking-widest btn-grad disabled:opacity-50"
      >
        {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Zap className="h-4 w-4" />}
        {loading ? "Building plan…" : "Build my plan"}
      </button>

      {plan && (
        <div className="mt-10 space-y-6">
          <div className="rounded-2xl border border-primary/40 bg-primary/5 p-6">
            <div className="font-display text-xl font-bold">{plan.headline}</div>
            <p className="mt-2 text-sm text-muted-foreground">{plan.strategy}</p>
            <div className="mt-4 flex flex-wrap gap-2">
              <button
                onClick={copyPlan}
                className="inline-flex items-center gap-2 rounded-full border border-border bg-surface px-4 py-2 font-mono text-[11px] font-bold uppercase tracking-widest text-muted-foreground transition-colors hover:border-primary hover:text-primary"
              >
                {copied ? (
                  <Check className="h-3.5 w-3.5 text-success" />
                ) : (
                  <Copy className="h-3.5 w-3.5" />
                )}
                {copied ? "Copied" : "Copy plan"}
              </button>
              <button
                onClick={downloadPlan}
                className="inline-flex items-center gap-2 rounded-full border border-border bg-surface px-4 py-2 font-mono text-[11px] font-bold uppercase tracking-widest text-muted-foreground transition-colors hover:border-primary hover:text-primary"
              >
                <Download className="h-3.5 w-3.5" />
                Download .txt
              </button>
            </div>
          </div>
          <div className="grid gap-3 md:grid-cols-2">
            {plan.days?.map((d) => (
              <div key={d.day} className="panel rounded-xl p-4">
                <div className="flex items-center justify-between">
                  <div className="font-mono text-[11px] uppercase tracking-widest text-primary">
                    {mode === "crash" ? `Block ${d.day}` : `Day ${d.day}`}
                  </div>
                  <span className="font-mono text-xs text-muted-foreground">{d.hours}h</span>
                </div>
                <div className="mt-1 font-bold">{d.focus}</div>
                <div className="mt-2 text-xs text-muted-foreground">
                  Topics: {d.topics?.join(", ")}
                </div>
                <ul className="mt-3 list-disc pl-5 text-sm text-foreground/80">
                  {d.tasks?.map((t, i) => (
                    <li key={i}>{t}</li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
          {plan.skip?.length ? (
            <div className="panel rounded-xl p-4">
              <div className="font-mono text-[11px] uppercase tracking-widest text-red-400">
                // Skip for now
              </div>
              <div className="mt-2 text-sm">{plan.skip.join(" · ")}</div>
            </div>
          ) : null}
        </div>
      )}
    </section>
  );
}
