import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { Loader2, Route as RouteIcon, Sparkles, Milestone, Wrench, FolderGit2, Briefcase } from "lucide-react";
import { Navbar } from "@/components/site/Navbar";
import { Marquee } from "@/components/site/Marquee";
import { Footer } from "@/components/site/Footer";
import { callEmoIq, type RoadmapResult } from "@/lib/emoiq/api";

export const Route = createFileRoute("/roadmap")({
  head: () => ({
    meta: [
      { title: "AI Roadmap Generator — EMO Learners" },
      { name: "description", content: "Get a personalized week-by-week study roadmap for your branch, semester, and career goal — generated by AI." },
      { property: "og:title", content: "AI Roadmap Generator — EMO Learners" },
      { property: "og:description", content: "Personalized week-by-week learning roadmaps for Indian engineering students." },
    ],
  }),
  component: RoadmapPage,
});

const BRANCHES = ["CSE", "IT", "AIML", "ECE", "EE", "Mechanical", "Civil"] as const;

function RoadmapPage() {
  const [branch, setBranch] = useState<string>("CSE");
  const [semester, setSemester] = useState<number>(5);
  const [goal, setGoal] = useState("Placement-ready software engineer");
  const [subjects, setSubjects] = useState("");
  const [hours, setHours] = useState(12);
  const [weeks, setWeeks] = useState(12);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<RoadmapResult | null>(null);

  async function generate() {
    setLoading(true);
    setResult(null);
    try {
      const r = await callEmoIq<RoadmapResult>("roadmap", {
        branch,
        semester,
        subjects: subjects.split(",").map((s) => s.trim()).filter(Boolean),
        goal,
        hoursPerWeek: hours,
        weeks,
      });
      setResult(r);
      try {
        localStorage.setItem("emo:last-roadmap", JSON.stringify({ at: Date.now(), branch, semester, weeks, title: r?.title }));
      } catch {}
      toast.success("Roadmap ready");
    } catch (e) {
      toast.error((e as Error).message);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen">
      <Marquee />
      <Navbar />

      <section className="relative overflow-hidden px-4 pb-10 pt-16">
        <div className="pointer-events-none absolute inset-0 grid-bg opacity-40" />
        <div className="pointer-events-none absolute inset-0 radial-glow" />
        <div className="relative mx-auto max-w-5xl">
          <div className="inline-flex items-center gap-2 rounded-full border border-primary/40 bg-primary/10 px-3 py-1 font-mono text-[10px] uppercase tracking-widest text-primary">
            <RouteIcon className="h-3 w-3" /> AI Roadmap · Personalized
          </div>
          <h1 className="mt-4 font-display text-4xl font-extrabold uppercase leading-[0.9] tracking-tighter md:text-6xl">
            Your <span className="italic text-primary">week-by-week</span> plan
          </h1>
          <p className="mt-4 max-w-2xl text-muted-foreground">
            Tell us your branch, semester, and goal. Get a week-wise roadmap with topics, projects, skills, and placement prep milestones.
          </p>
        </div>
      </section>

      <section className="px-4 pb-14">
        <div className="mx-auto grid max-w-5xl gap-4 rounded-2xl border border-border bg-surface/40 p-6 md:grid-cols-2">
          <Field label="Branch">
            <select value={branch} onChange={(e) => setBranch(e.target.value)} className="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm outline-none focus:border-primary">
              {BRANCHES.map((b) => <option key={b}>{b}</option>)}
            </select>
          </Field>
          <Field label="Semester">
            <input type="number" min={1} max={8} value={semester} onChange={(e) => setSemester(Number(e.target.value))}
              className="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm outline-none focus:border-primary" />
          </Field>
          <Field label="Career goal">
            <input value={goal} onChange={(e) => setGoal(e.target.value)}
              className="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm outline-none focus:border-primary" />
          </Field>
          <Field label="Subjects (optional, comma-separated)">
            <input value={subjects} onChange={(e) => setSubjects(e.target.value)} placeholder="DSA, DBMS, OS…"
              className="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm outline-none focus:border-primary" />
          </Field>
          <Field label="Hours per week">
            <input type="number" min={3} max={40} value={hours} onChange={(e) => setHours(Number(e.target.value))}
              className="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm outline-none focus:border-primary" />
          </Field>
          <Field label="Weeks">
            <input type="number" min={2} max={16} value={weeks} onChange={(e) => setWeeks(Number(e.target.value))}
              className="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm outline-none focus:border-primary" />
          </Field>
          <div className="md:col-span-2">
            <button onClick={generate} disabled={loading}
              className="inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3 font-mono text-xs font-bold uppercase tracking-widest text-primary-foreground shadow-brand disabled:opacity-50">
              {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
              {loading ? "Generating…" : "Generate roadmap"}
            </button>
          </div>
        </div>
      </section>

      {result && (
        <section className="px-4 pb-24">
          <div className="mx-auto max-w-5xl space-y-6">
            <div className="rounded-2xl border border-primary/40 bg-primary/5 p-6">
              <div className="font-mono text-[11px] uppercase tracking-widest text-primary">Roadmap</div>
              <h2 className="mt-2 font-display text-2xl font-extrabold uppercase md:text-3xl">{result.title}</h2>
              <p className="mt-3 text-sm text-muted-foreground">{result.summary}</p>
            </div>

            <div>
              <SectionTitle icon={Milestone} title="Weekly milestones" />
              <ol className="mt-4 space-y-3">
                {result.milestones?.map((m) => (
                  <li key={m.week} className="rounded-2xl border border-border bg-surface/50 p-5">
                    <div className="flex items-center justify-between">
                      <div className="font-mono text-[11px] uppercase tracking-widest text-primary">Week {m.week}</div>
                      <div className="text-xs text-muted-foreground">{m.subjects?.join(" · ")}</div>
                    </div>
                    <h3 className="mt-1 font-display text-lg font-extrabold uppercase">{m.theme}</h3>
                    <div className="mt-3 grid gap-3 md:grid-cols-3">
                      <MiniList label="Topics" items={m.topics} />
                      <MiniList label="Outcomes" items={m.outcomes} />
                      <MiniList label="Resources" items={m.resources} />
                    </div>
                  </li>
                ))}
              </ol>
            </div>

            <div className="grid gap-6 md:grid-cols-2">
              <div>
                <SectionTitle icon={Wrench} title="Key skills" />
                <ul className="mt-4 space-y-2">
                  {result.skills?.map((s, i) => (
                    <li key={i} className="rounded-xl border border-border bg-surface/50 p-4">
                      <div className="font-semibold">{s.name}</div>
                      <div className="mt-1 text-xs text-muted-foreground">{s.why}</div>
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <SectionTitle icon={FolderGit2} title="Projects to build" />
                <ul className="mt-4 space-y-2">
                  {result.projects?.map((p, i) => (
                    <li key={i} className="rounded-xl border border-border bg-surface/50 p-4">
                      <div className="font-semibold">{p.name}</div>
                      <div className="mt-1 text-xs text-muted-foreground">{p.brief}</div>
                      <div className="mt-2 flex flex-wrap gap-1">
                        {p.stack?.map((t) => <span key={t} className="rounded-full border border-border px-2 py-0.5 font-mono text-[10px] uppercase tracking-widest text-muted-foreground">{t}</span>)}
                      </div>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            <div>
              <SectionTitle icon={Briefcase} title="Placement prep" />
              <ul className="mt-4 grid gap-2 md:grid-cols-2">
                {result.placement_prep?.map((p, i) => (
                  <li key={i} className="rounded-xl border border-border bg-surface/50 px-4 py-3 text-sm">{p}</li>
                ))}
              </ul>
            </div>
          </div>
        </section>
      )}

      <Footer />
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="mb-2 block font-mono text-[11px] uppercase tracking-widest text-primary">{label}</span>
      {children}
    </label>
  );
}

function SectionTitle({ icon: Icon, title }: { icon: React.ComponentType<{ className?: string }>; title: string }) {
  return (
    <div className="flex items-center gap-2">
      <Icon className="h-5 w-5 text-primary" />
      <h3 className="font-display text-xl font-extrabold uppercase tracking-tighter">{title}</h3>
    </div>
  );
}

function MiniList({ label, items }: { label: string; items?: string[] }) {
  if (!items?.length) return null;
  return (
    <div>
      <div className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">{label}</div>
      <ul className="mt-1 space-y-1 text-sm">
        {items.map((it, i) => <li key={i} className="flex gap-2"><span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />{it}</li>)}
      </ul>
    </div>
  );
}
