import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import {
  Loader2,
  Route as RouteIcon,
  Sparkles,
  Milestone,
  Wrench,
  FolderGit2,
  Briefcase,
  Download,
  FileJson,
  RefreshCw,
  AlertTriangle,
  ClipboardList,
  Copy,
} from "lucide-react";
import { Navbar } from "@/components/site/Navbar";
import { Marquee } from "@/components/site/Marquee";
import { Footer } from "@/components/site/Footer";
import { callEmoIq, type RoadmapResult } from "@/lib/emoiq/api";

export const Route = createFileRoute("/roadmap")({
  head: () => ({
    meta: [
      { title: "AI Roadmap Generator — EMO Learners" },
      { name: "description", content: "Get a personalized week-by-week study roadmap for your branch, semester, and career goal — generated by AI." },
      { property: "og:title", content: "AI Roadmap Generator — EMO Learners" },
      { property: "og:description", content: "Personalized week-by-week learning roadmaps for Indian engineering students." },
    ],
  }),
  component: RoadmapPage,
});

const BRANCHES = ["CSE", "IT", "AIML", "ECE", "EE", "Mechanical", "Civil"] as const;

function friendlyError(msg: string): string {
  const m = msg.toLowerCase();
  if (m.includes("failed to fetch") || m.includes("network")) return "Network hiccup. Check your connection and try again.";
  if (m.includes("401") || m.includes("unauthor")) return "Please sign in to generate a roadmap.";
  if (m.includes("429") || m.includes("rate")) return "You're going a bit fast — wait a moment and retry.";
  if (m.includes("timeout")) return "The AI took too long. Try fewer weeks or retry.";
  return msg || "Something went wrong. Please try again.";
}

function RoadmapPage() {
  const [branch, setBranch] = useState<string>("CSE");
  const [semester, setSemester] = useState<number>(5);
  const [goal, setGoal] = useState("Placement-ready software engineer");
  const [subjects, setSubjects] = useState("");
  const [hours, setHours] = useState(12);
  const [weeks, setWeeks] = useState(12);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<RoadmapResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setResult(null);
    setError(null);
    try {
      const r = await callEmoIq<RoadmapResult>("roadmap", {
        branch,
        semester,
        subjects: subjects.split(",").map((s) => s.trim()).filter(Boolean),
        goal,
        hoursPerWeek: hours,
        weeks,
      });
      setResult(r);
      try {
        localStorage.setItem("emo:last-roadmap", JSON.stringify({ at: Date.now(), branch, semester, weeks, title: r?.title }));
      } catch {}
      toast.success("Roadmap ready");
    } catch (e) {
      const nice = friendlyError((e as Error).message);
      setError(nice);
      toast.error(nice);
    } finally {
      setLoading(false);
    }
  }

  const summary = useMemo(() => {
    if (!result) return null;
    const totalTopics = result.milestones?.reduce((a, m) => a + (m.topics?.length ?? 0), 0) ?? 0;
    const totalOutcomes = result.milestones?.reduce((a, m) => a + (m.outcomes?.length ?? 0), 0) ?? 0;
    const subjectsSet = new Set<string>();
    result.milestones?.forEach((m) => m.subjects?.forEach((s) => subjectsSet.add(s)));
    return {
      weeks: result.milestones?.length ?? 0,
      totalTopics,
      totalOutcomes,
      subjects: [...subjectsSet],
      skills: result.skills?.length ?? 0,
      projects: result.projects?.length ?? 0,
      placement: result.placement_prep?.length ?? 0,
      estHours: (result.milestones?.length ?? 0) * hours,
    };
  }, [result, hours]);

  function buildMarkdown(r: RoadmapResult): string {
    const lines: string[] = [];
    lines.push(`# ${r.title}`, "", r.summary, "");
    lines.push(`**Branch:** ${branch}  \n**Semester:** ${semester}  \n**Goal:** ${goal}  \n**Hours/week:** ${hours}  \n**Weeks:** ${weeks}`, "");
    lines.push(`## Weekly Milestones`, "");
    r.milestones?.forEach((m) => {
      lines.push(`### Week ${m.week} — ${m.theme}`);
      if (m.subjects?.length) lines.push(`_Subjects:_ ${m.subjects.join(", ")}`);
      if (m.topics?.length) lines.push(`\n**Topics**\n${m.topics.map((t) => `- ${t}`).join("\n")}`);
      if (m.outcomes?.length) lines.push(`\n**Outcomes**\n${m.outcomes.map((t) => `- ${t}`).join("\n")}`);
      if (m.resources?.length) lines.push(`\n**Resources**\n${m.resources.map((t) => `- ${t}`).join("\n")}`);
      lines.push("");
    });
    if (r.skills?.length) {
      lines.push(`## Key Skills`, "");
      r.skills.forEach((s) => lines.push(`- **${s.name}** — ${s.why}`));
      lines.push("");
    }
    if (r.projects?.length) {
      lines.push(`## Projects`, "");
      r.projects.forEach((p) => lines.push(`- **${p.name}** — ${p.brief} _(stack: ${p.stack?.join(", ") ?? "—"})_`));
      lines.push("");
    }
    if (r.placement_prep?.length) {
      lines.push(`## Placement Prep`, "");
      r.placement_prep.forEach((p) => lines.push(`- ${p}`));
    }
    return lines.join("\n");
  }

  function download(name: string, data: string, type: string) {
    const blob = new Blob([data], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = name;
    a.click();
    URL.revokeObjectURL(url);
  }

  function exportMarkdown() {
    if (!result) return;
    download(`roadmap-${branch}-sem${semester}.md`, buildMarkdown(result), "text/markdown");
    toast.success("Markdown downloaded");
  }
  function exportJson() {
    if (!result) return;
    download(`roadmap-${branch}-sem${semester}.json`, JSON.stringify({ meta: { branch, semester, goal, hours, weeks }, ...result }, null, 2), "application/json");
    toast.success("JSON downloaded");
  }
  async function copyMarkdown() {
    if (!result) return;
    try {
      await navigator.clipboard.writeText(buildMarkdown(result));
      toast.success("Copied to clipboard");
    } catch {
      toast.error("Clipboard blocked by browser");
    }
  }

  return (
    <div className="min-h-screen">
      <Marquee />
      <Navbar />

      <section className="relative overflow-hidden px-4 pb-10 pt-16">
        <div className="pointer-events-none absolute inset-0 grid-bg opacity-40" />
        <div className="pointer-events-none absolute inset-0 radial-glow" />
        <div className="relative mx-auto max-w-5xl">
          <div className="inline-flex items-center gap-2 rounded-full border border-primary/40 bg-primary/10 px-3 py-1 font-mono text-[10px] uppercase tracking-widest text-primary">
            <RouteIcon className="h-3 w-3" /> AI Roadmap · Personalized
          </div>
          <h1 className="mt-4 font-display text-4xl font-extrabold uppercase leading-[0.9] tracking-tighter md:text-6xl">
            Your <span className="italic text-primary">week-by-week</span> plan
          </h1>
          <p className="mt-4 max-w-2xl text-muted-foreground">
            Tell us your branch, semester, and goal. Get a week-wise roadmap with topics, projects, skills, and placement prep milestones.
          </p>
        </div>
      </section>

      <section className="px-4 pb-14">
        <div className="mx-auto grid max-w-5xl gap-4 rounded-2xl border border-border bg-surface/40 p-6 md:grid-cols-2">
          <Field label="Branch">
            <select value={branch} onChange={(e) => setBranch(e.target.value)} className="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm outline-none focus:border-primary">
              {BRANCHES.map((b) => <option key={b}>{b}</option>)}
            </select>
          </Field>
          <Field label="Semester">
            <input type="number" min={1} max={8} value={semester} onChange={(e) => setSemester(Number(e.target.value))}
              className="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm outline-none focus:border-primary" />
          </Field>
          <Field label="Career goal">
            <input value={goal} onChange={(e) => setGoal(e.target.value)}
              className="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm outline-none focus:border-primary" />
          </Field>
          <Field label="Subjects (optional, comma-separated)">
            <input value={subjects} onChange={(e) => setSubjects(e.target.value)} placeholder="DSA, DBMS, OS…"
              className="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm outline-none focus:border-primary" />
          </Field>
          <Field label="Hours per week">
            <input type="number" min={3} max={40} value={hours} onChange={(e) => setHours(Number(e.target.value))}
              className="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm outline-none focus:border-primary" />
          </Field>
          <Field label="Weeks">
            <input type="number" min={2} max={16} value={weeks} onChange={(e) => setWeeks(Number(e.target.value))}
              className="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm outline-none focus:border-primary" />
          </Field>
          <div className="md:col-span-2 flex flex-wrap items-center gap-3">
            <button onClick={generate} disabled={loading}
              className="inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3 font-mono text-xs font-bold uppercase tracking-widest text-primary-foreground shadow-brand disabled:opacity-50">
              {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
              {loading ? "Generating…" : result ? "Regenerate" : "Generate roadmap"}
            </button>
            {error && !loading && (
              <button onClick={generate}
                className="inline-flex items-center gap-2 rounded-full border border-border bg-surface px-5 py-3 font-mono text-xs font-bold uppercase tracking-widest hover:border-primary">
                <RefreshCw className="h-4 w-4" /> Retry
              </button>
            )}
          </div>
        </div>
      </section>

      {loading && (
        <section className="px-4 pb-24">
          <div className="mx-auto max-w-5xl space-y-6">
            <SkeletonBlock className="h-32" />
            <SkeletonBlock className="h-8 w-56" />
            <div className="grid gap-3">
              {Array.from({ length: 3 }).map((_, i) => <SkeletonBlock key={i} className="h-40" />)}
            </div>
            <div className="grid gap-6 md:grid-cols-2">
              <SkeletonBlock className="h-64" />
              <SkeletonBlock className="h-64" />
            </div>
          </div>
        </section>
      )}

      {error && !loading && !result && (
        <section className="px-4 pb-24">
          <div className="mx-auto max-w-5xl">
            <div className="flex flex-col items-start gap-3 rounded-2xl border border-destructive/40 bg-destructive/10 p-6 md:flex-row md:items-center md:justify-between">
              <div className="flex items-start gap-3">
                <AlertTriangle className="mt-0.5 h-5 w-5 text-destructive" />
                <div>
                  <div className="font-display text-lg font-extrabold uppercase">Couldn't generate roadmap</div>
                  <div className="mt-1 text-sm text-muted-foreground">{error}</div>
                </div>
              </div>
              <button onClick={generate}
                className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-2.5 font-mono text-xs font-bold uppercase tracking-widest text-primary-foreground">
                <RefreshCw className="h-4 w-4" /> Try again
              </button>
            </div>
          </div>
        </section>
      )}

      {result && !loading && (
        <section className="px-4 pb-24">
          <div className="mx-auto max-w-5xl space-y-6">
            <div className="rounded-2xl border border-primary/40 bg-primary/5 p-6">
              <div className="flex flex-wrap items-start justify-between gap-4">
                <div>
                  <div className="font-mono text-[11px] uppercase tracking-widest text-primary">Roadmap</div>
                  <h2 className="mt-2 font-display text-2xl font-extrabold uppercase md:text-3xl">{result.title}</h2>
                  <p className="mt-3 max-w-2xl text-sm text-muted-foreground">{result.summary}</p>
                </div>
                <div className="flex flex-wrap gap-2">
                  <button onClick={exportMarkdown}
                    className="inline-flex items-center gap-2 rounded-full border border-border bg-surface px-4 py-2 font-mono text-[11px] font-bold uppercase tracking-widest hover:border-primary">
                    <Download className="h-3.5 w-3.5" /> Export .md
                  </button>
                  <button onClick={exportJson}
                    className="inline-flex items-center gap-2 rounded-full border border-border bg-surface px-4 py-2 font-mono text-[11px] font-bold uppercase tracking-widest hover:border-primary">
                    <FileJson className="h-3.5 w-3.5" /> Export .json
                  </button>
                  <button onClick={copyMarkdown}
                    className="inline-flex items-center gap-2 rounded-full border border-border bg-surface px-4 py-2 font-mono text-[11px] font-bold uppercase tracking-widest hover:border-primary">
                    <Copy className="h-3.5 w-3.5" /> Copy
                  </button>
                </div>
              </div>
            </div>

            {summary && (
              <div className="rounded-2xl border border-border bg-surface/40 p-6">
                <div className="flex items-center gap-2">
                  <ClipboardList className="h-5 w-5 text-primary" />
                  <h3 className="font-display text-xl font-extrabold uppercase tracking-tighter">Summary</h3>
                </div>
                <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                  <SummaryStat label="Weeks" value={summary.weeks} />
                  <SummaryStat label="Est. hours" value={summary.estHours} />
                  <SummaryStat label="Topics" value={summary.totalTopics} />
                  <SummaryStat label="Outcomes" value={summary.totalOutcomes} />
                  <SummaryStat label="Skills" value={summary.skills} />
                  <SummaryStat label="Projects" value={summary.projects} />
                  <SummaryStat label="Placement items" value={summary.placement} />
                  <SummaryStat label="Subjects covered" value={summary.subjects.length} />
                </div>
                {summary.subjects.length > 0 && (
                  <div className="mt-5 flex flex-wrap gap-1.5">
                    {summary.subjects.map((s) => (
                      <span key={s} className="rounded-full border border-primary/40 bg-primary/10 px-3 py-0.5 font-mono text-[10px] uppercase tracking-widest text-primary">{s}</span>
                    ))}
                  </div>
                )}
              </div>
            )}

            <div>
              <SectionTitle icon={Milestone} title="Weekly milestones" />
              <ol className="mt-4 space-y-3">
                {result.milestones?.map((m) => (
                  <li key={m.week} className="rounded-2xl border border-border bg-surface/50 p-5">
                    <div className="flex items-center justify-between">
                      <div className="font-mono text-[11px] uppercase tracking-widest text-primary">Week {m.week}</div>
                      <div className="text-xs text-muted-foreground">{m.subjects?.join(" · ")}</div>
                    </div>
                    <h3 className="mt-1 font-display text-lg font-extrabold uppercase">{m.theme}</h3>
                    <div className="mt-3 grid gap-3 md:grid-cols-3">
                      <MiniList label="Topics" items={m.topics} />
                      <MiniList label="Outcomes" items={m.outcomes} />
                      <MiniList label="Resources" items={m.resources} />
                    </div>
                  </li>
                ))}
              </ol>
            </div>

            <div className="grid gap-6 md:grid-cols-2">
              <div>
                <SectionTitle icon={Wrench} title="Key skills" />
                <ul className="mt-4 space-y-2">
                  {result.skills?.map((s, i) => (
                    <li key={i} className="rounded-xl border border-border bg-surface/50 p-4">
                      <div className="font-semibold">{s.name}</div>
                      <div className="mt-1 text-xs text-muted-foreground">{s.why}</div>
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <SectionTitle icon={FolderGit2} title="Projects to build" />
                <ul className="mt-4 space-y-2">
                  {result.projects?.map((p, i) => (
                    <li key={i} className="rounded-xl border border-border bg-surface/50 p-4">
                      <div className="font-semibold">{p.name}</div>
                      <div className="mt-1 text-xs text-muted-foreground">{p.brief}</div>
                      <div className="mt-2 flex flex-wrap gap-1">
                        {p.stack?.map((t) => <span key={t} className="rounded-full border border-border px-2 py-0.5 font-mono text-[10px] uppercase tracking-widest text-muted-foreground">{t}</span>)}
                      </div>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            <div>
              <SectionTitle icon={Briefcase} title="Placement prep" />
              <ul className="mt-4 grid gap-2 md:grid-cols-2">
                {result.placement_prep?.map((p, i) => (
                  <li key={i} className="rounded-xl border border-border bg-surface/50 px-4 py-3 text-sm">{p}</li>
                ))}
              </ul>
            </div>
          </div>
        </section>
      )}

      <Footer />
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="mb-2 block font-mono text-[11px] uppercase tracking-widest text-primary">{label}</span>
      {children}
    </label>
  );
}

function SectionTitle({ icon: Icon, title }: { icon: React.ComponentType<{ className?: string }>; title: string }) {
  return (
    <div className="flex items-center gap-2">
      <Icon className="h-5 w-5 text-primary" />
      <h3 className="font-display text-xl font-extrabold uppercase tracking-tighter">{title}</h3>
    </div>
  );
}

function MiniList({ label, items }: { label: string; items?: string[] }) {
  if (!items?.length) return null;
  return (
    <div>
      <div className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">{label}</div>
      <ul className="mt-1 space-y-1 text-sm">
        {items.map((it, i) => <li key={i} className="flex gap-2"><span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />{it}</li>)}
      </ul>
    </div>
  );
}

function SummaryStat({ label, value }: { label: string; value: number }) {
  return (
    <div className="rounded-xl border border-border bg-surface/60 p-4">
      <div className="font-display text-2xl font-extrabold">{value}</div>
      <div className="mt-1 font-mono text-[10px] uppercase tracking-widest text-muted-foreground">{label}</div>
    </div>
  );
}

function SkeletonBlock({ className = "" }: { className?: string }) {
  return <div className={`animate-pulse rounded-2xl border border-border bg-surface/40 ${className}`} />;
}
