/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as EmoiqRouteImport } from './routes/emoiq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes.index'
import { Route as PlacementIndexRouteImport } from './routes/placement.index'
import { Route as EmoiqIndexRouteImport } from './routes/emoiq.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as TestsSlugRouteImport } from './routes/tests.$slug'
import { Route as QuizzesSlugRouteImport } from './routes/quizzes.$slug'
import { Route as PlacementResumeRouteImport } from './routes/placement.resume'
import { Route as PlacementInterviewRouteImport } from './routes/placement.interview'
import { Route as PlacementCodingRouteImport } from './routes/placement.coding'
import { Route as PlacementAptitudeRouteImport } from './routes/placement.aptitude'
import { Route as EmoiqQuizRouteImport } from './routes/emoiq.quiz'
import { Route as EmoiqPredictRouteImport } from './routes/emoiq.predict'
import { Route as EmoiqPlanRouteImport } from './routes/emoiq.plan'
import { Route as EmoiqDoubtRouteImport } from './routes/emoiq.doubt'
import { Route as EmoiqAnalyzeRouteImport } from './routes/emoiq.analyze'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const EmoiqRoute = EmoiqRouteImport.update({
  id: '/emoiq',
  path: '/emoiq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementIndexRoute = PlacementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlacementRoute,
} as any)
const EmoiqIndexRoute = EmoiqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmoiqRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsSlugRoute = TestsSlugRouteImport.update({
  id: '/tests/$slug',
  path: '/tests/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesSlugRoute = QuizzesSlugRouteImport.update({
  id: '/quizzes/$slug',
  path: '/quizzes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementResumeRoute = PlacementResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => PlacementRoute,
} as any)
const PlacementInterviewRoute = PlacementInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => PlacementRoute,
} as any)
const PlacementCodingRoute = PlacementCodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => PlacementRoute,
} as any)
const PlacementAptitudeRoute = PlacementAptitudeRouteImport.update({
  id: '/aptitude',
  path: '/aptitude',
  getParentRoute: () => PlacementRoute,
} as any)
const EmoiqQuizRoute = EmoiqQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => EmoiqRoute,
} as any)
const EmoiqPredictRoute = EmoiqPredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => EmoiqRoute,
} as any)
const EmoiqPlanRoute = EmoiqPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => EmoiqRoute,
} as any)
const EmoiqDoubtRoute = EmoiqDoubtRouteImport.update({
  id: '/doubt',
  path: '/doubt',
  getParentRoute: () => EmoiqRoute,
} as any)
const EmoiqAnalyzeRoute = EmoiqAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => EmoiqRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/auth': typeof AuthRoute
  '/challenge': typeof ChallengeRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/emoiq': typeof EmoiqRouteWithChildren
  '/internships': typeof InternshipsRoute
  '/join': typeof JoinRoute
  '/placement': typeof PlacementRouteWithChildren
  '/practice': typeof PracticeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/emoiq/analyze': typeof EmoiqAnalyzeRoute
  '/emoiq/doubt': typeof EmoiqDoubtRoute
  '/emoiq/plan': typeof EmoiqPlanRoute
  '/emoiq/predict': typeof EmoiqPredictRoute
  '/emoiq/quiz': typeof EmoiqQuizRoute
  '/placement/aptitude': typeof PlacementAptitudeRoute
  '/placement/coding': typeof PlacementCodingRoute
  '/placement/interview': typeof PlacementInterviewRoute
  '/placement/resume': typeof PlacementResumeRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/tests/$slug': typeof TestsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/emoiq/': typeof EmoiqIndexRoute
  '/placement/': typeof PlacementIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/auth': typeof AuthRoute
  '/challenge': typeof ChallengeRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/internships': typeof InternshipsRoute
  '/join': typeof JoinRoute
  '/practice': typeof PracticeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/emoiq/analyze': typeof EmoiqAnalyzeRoute
  '/emoiq/doubt': typeof EmoiqDoubtRoute
  '/emoiq/plan': typeof EmoiqPlanRoute
  '/emoiq/predict': typeof EmoiqPredictRoute
  '/emoiq/quiz': typeof EmoiqQuizRoute
  '/placement/aptitude': typeof PlacementAptitudeRoute
  '/placement/coding': typeof PlacementCodingRoute
  '/placement/interview': typeof PlacementInterviewRoute
  '/placement/resume': typeof PlacementResumeRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/tests/$slug': typeof TestsSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/emoiq': typeof EmoiqIndexRoute
  '/placement': typeof PlacementIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/tests': typeof TestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/auth': typeof AuthRoute
  '/challenge': typeof ChallengeRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/emoiq': typeof EmoiqRouteWithChildren
  '/internships': typeof InternshipsRoute
  '/join': typeof JoinRoute
  '/placement': typeof PlacementRouteWithChildren
  '/practice': typeof PracticeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/emoiq/analyze': typeof EmoiqAnalyzeRoute
  '/emoiq/doubt': typeof EmoiqDoubtRoute
  '/emoiq/plan': typeof EmoiqPlanRoute
  '/emoiq/predict': typeof EmoiqPredictRoute
  '/emoiq/quiz': typeof EmoiqQuizRoute
  '/placement/aptitude': typeof PlacementAptitudeRoute
  '/placement/coding': typeof PlacementCodingRoute
  '/placement/interview': typeof PlacementInterviewRoute
  '/placement/resume': typeof PlacementResumeRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/tests/$slug': typeof TestsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/emoiq/': typeof EmoiqIndexRoute
  '/placement/': typeof PlacementIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-assistant'
    | '/auth'
    | '/challenge'
    | '/contact'
    | '/dashboard'
    | '/emoiq'
    | '/internships'
    | '/join'
    | '/placement'
    | '/practice'
    | '/privacy-policy'
    | '/reset-password'
    | '/resources'
    | '/sitemap.xml'
    | '/courses/$slug'
    | '/emoiq/analyze'
    | '/emoiq/doubt'
    | '/emoiq/plan'
    | '/emoiq/predict'
    | '/emoiq/quiz'
    | '/placement/aptitude'
    | '/placement/coding'
    | '/placement/interview'
    | '/placement/resume'
    | '/quizzes/$slug'
    | '/tests/$slug'
    | '/courses/'
    | '/emoiq/'
    | '/placement/'
    | '/quizzes/'
    | '/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-assistant'
    | '/auth'
    | '/challenge'
    | '/contact'
    | '/dashboard'
    | '/internships'
    | '/join'
    | '/practice'
    | '/privacy-policy'
    | '/reset-password'
    | '/resources'
    | '/sitemap.xml'
    | '/courses/$slug'
    | '/emoiq/analyze'
    | '/emoiq/doubt'
    | '/emoiq/plan'
    | '/emoiq/predict'
    | '/emoiq/quiz'
    | '/placement/aptitude'
    | '/placement/coding'
    | '/placement/interview'
    | '/placement/resume'
    | '/quizzes/$slug'
    | '/tests/$slug'
    | '/courses'
    | '/emoiq'
    | '/placement'
    | '/quizzes'
    | '/tests'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai-assistant'
    | '/auth'
    | '/challenge'
    | '/contact'
    | '/dashboard'
    | '/emoiq'
    | '/internships'
    | '/join'
    | '/placement'
    | '/practice'
    | '/privacy-policy'
    | '/reset-password'
    | '/resources'
    | '/sitemap.xml'
    | '/courses/$slug'
    | '/emoiq/analyze'
    | '/emoiq/doubt'
    | '/emoiq/plan'
    | '/emoiq/predict'
    | '/emoiq/quiz'
    | '/placement/aptitude'
    | '/placement/coding'
    | '/placement/interview'
    | '/placement/resume'
    | '/quizzes/$slug'
    | '/tests/$slug'
    | '/courses/'
    | '/emoiq/'
    | '/placement/'
    | '/quizzes/'
    | '/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AuthRoute: typeof AuthRoute
  ChallengeRoute: typeof ChallengeRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EmoiqRoute: typeof EmoiqRouteWithChildren
  InternshipsRoute: typeof InternshipsRoute
  JoinRoute: typeof JoinRoute
  PlacementRoute: typeof PlacementRouteWithChildren
  PracticeRoute: typeof PracticeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  QuizzesSlugRoute: typeof QuizzesSlugRoute
  TestsSlugRoute: typeof TestsSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emoiq': {
      id: '/emoiq'
      path: '/emoiq'
      fullPath: '/emoiq'
      preLoaderRoute: typeof EmoiqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement/': {
      id: '/placement/'
      path: '/'
      fullPath: '/placement/'
      preLoaderRoute: typeof PlacementIndexRouteImport
      parentRoute: typeof PlacementRoute
    }
    '/emoiq/': {
      id: '/emoiq/'
      path: '/'
      fullPath: '/emoiq/'
      preLoaderRoute: typeof EmoiqIndexRouteImport
      parentRoute: typeof EmoiqRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$slug': {
      id: '/tests/$slug'
      path: '/tests/$slug'
      fullPath: '/tests/$slug'
      preLoaderRoute: typeof TestsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$slug': {
      id: '/quizzes/$slug'
      path: '/quizzes/$slug'
      fullPath: '/quizzes/$slug'
      preLoaderRoute: typeof QuizzesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement/resume': {
      id: '/placement/resume'
      path: '/resume'
      fullPath: '/placement/resume'
      preLoaderRoute: typeof PlacementResumeRouteImport
      parentRoute: typeof PlacementRoute
    }
    '/placement/interview': {
      id: '/placement/interview'
      path: '/interview'
      fullPath: '/placement/interview'
      preLoaderRoute: typeof PlacementInterviewRouteImport
      parentRoute: typeof PlacementRoute
    }
    '/placement/coding': {
      id: '/placement/coding'
      path: '/coding'
      fullPath: '/placement/coding'
      preLoaderRoute: typeof PlacementCodingRouteImport
      parentRoute: typeof PlacementRoute
    }
    '/placement/aptitude': {
      id: '/placement/aptitude'
      path: '/aptitude'
      fullPath: '/placement/aptitude'
      preLoaderRoute: typeof PlacementAptitudeRouteImport
      parentRoute: typeof PlacementRoute
    }
    '/emoiq/quiz': {
      id: '/emoiq/quiz'
      path: '/quiz'
      fullPath: '/emoiq/quiz'
      preLoaderRoute: typeof EmoiqQuizRouteImport
      parentRoute: typeof EmoiqRoute
    }
    '/emoiq/predict': {
      id: '/emoiq/predict'
      path: '/predict'
      fullPath: '/emoiq/predict'
      preLoaderRoute: typeof EmoiqPredictRouteImport
      parentRoute: typeof EmoiqRoute
    }
    '/emoiq/plan': {
      id: '/emoiq/plan'
      path: '/plan'
      fullPath: '/emoiq/plan'
      preLoaderRoute: typeof EmoiqPlanRouteImport
      parentRoute: typeof EmoiqRoute
    }
    '/emoiq/doubt': {
      id: '/emoiq/doubt'
      path: '/doubt'
      fullPath: '/emoiq/doubt'
      preLoaderRoute: typeof EmoiqDoubtRouteImport
      parentRoute: typeof EmoiqRoute
    }
    '/emoiq/analyze': {
      id: '/emoiq/analyze'
      path: '/analyze'
      fullPath: '/emoiq/analyze'
      preLoaderRoute: typeof EmoiqAnalyzeRouteImport
      parentRoute: typeof EmoiqRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EmoiqRouteChildren {
  EmoiqAnalyzeRoute: typeof EmoiqAnalyzeRoute
  EmoiqDoubtRoute: typeof EmoiqDoubtRoute
  EmoiqPlanRoute: typeof EmoiqPlanRoute
  EmoiqPredictRoute: typeof EmoiqPredictRoute
  EmoiqQuizRoute: typeof EmoiqQuizRoute
  EmoiqIndexRoute: typeof EmoiqIndexRoute
}

const EmoiqRouteChildren: EmoiqRouteChildren = {
  EmoiqAnalyzeRoute: EmoiqAnalyzeRoute,
  EmoiqDoubtRoute: EmoiqDoubtRoute,
  EmoiqPlanRoute: EmoiqPlanRoute,
  EmoiqPredictRoute: EmoiqPredictRoute,
  EmoiqQuizRoute: EmoiqQuizRoute,
  EmoiqIndexRoute: EmoiqIndexRoute,
}

const EmoiqRouteWithChildren = EmoiqRoute._addFileChildren(EmoiqRouteChildren)

interface PlacementRouteChildren {
  PlacementAptitudeRoute: typeof PlacementAptitudeRoute
  PlacementCodingRoute: typeof PlacementCodingRoute
  PlacementInterviewRoute: typeof PlacementInterviewRoute
  PlacementResumeRoute: typeof PlacementResumeRoute
  PlacementIndexRoute: typeof PlacementIndexRoute
}

const PlacementRouteChildren: PlacementRouteChildren = {
  PlacementAptitudeRoute: PlacementAptitudeRoute,
  PlacementCodingRoute: PlacementCodingRoute,
  PlacementInterviewRoute: PlacementInterviewRoute,
  PlacementResumeRoute: PlacementResumeRoute,
  PlacementIndexRoute: PlacementIndexRoute,
}

const PlacementRouteWithChildren = PlacementRoute._addFileChildren(
  PlacementRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AiAssistantRoute: AiAssistantRoute,
  AuthRoute: AuthRoute,
  ChallengeRoute: ChallengeRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EmoiqRoute: EmoiqRouteWithChildren,
  InternshipsRoute: InternshipsRoute,
  JoinRoute: JoinRoute,
  PlacementRoute: PlacementRouteWithChildren,
  PracticeRoute: PracticeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  QuizzesSlugRoute: QuizzesSlugRoute,
  TestsSlugRoute: TestsSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
